# Generated by Django 2.2.1 on 2019-05-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=50)),
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
