# Generated by Django 2.2.1 on 2019-05-24 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_id', models.UUIDField(verbose_name='Check ID')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('cheque', models.ImageField(blank=True, max_length=1000, null=True, upload_to='cheques/')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users', verbose_name='User that has issued the cheque')),
            ],
        ),
    ]
