# Generated by Django 2.2.1 on 2019-05-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque_generator', '0003_auto_20190524_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
