# Generated by Django 2.2.1 on 2019-05-24 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheque_generator', '0005_auto_20190524_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='cheque_id',
        ),
    ]
