# Generated by Django 2.2.1 on 2019-05-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque_generator', '0006_remove_cheque_cheque_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='amount',
            field=models.FloatField(),
        ),
    ]
